version: '3'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdb-irdesi-inscricao:/var/lib/postgresql/data
  app:
    build:
      context: ./
    env_file:
      - .env
    ports:
      - 3000:3000

volumes:
  pgdb-irdesi-inscricao:
